datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=UTF-8&jdbcCompliantTruncation=false&useOldAliasMetadataBehavior=true&useSSL=false
  username: root
  password: 123456
  minimum-idle: 10
  maximum-pool-size: 20
  connection-timeout: 30000
  poolName: BOOK-DB-POOL
  data-source-properties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

jpa:
  spring:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          current_session_context_class: thread
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true